package com.kcsj.pojo;

public class BookType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer btId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.bt_type
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String btType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.floor
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.character
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String character;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.bt_id
     *
     * @return the value of booktype.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getBtId() {
        return btId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.bt_id
     *
     * @param btId the value for booktype.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setBtId(Integer btId) {
        this.btId = btId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.bt_type
     *
     * @return the value of booktype.bt_type
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getBtType() {
        return btType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.bt_type
     *
     * @param btType the value for booktype.bt_type
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setBtType(String btType) {
        this.btType = btType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.floor
     *
     * @return the value of booktype.floor
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.floor
     *
     * @param floor the value for booktype.floor
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.character
     *
     * @return the value of booktype.character
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getCharacter() {
        return character;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.character
     *
     * @param character the value for booktype.character
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setCharacter(String character) {
        this.character = character;
    }
}