package com.kcsj.pojo;

import java.util.Date;

public class BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.bname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.author
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.press
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.presstime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date presstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.stock
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.loan_mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double loanMount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double mount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer btId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.picture
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private byte[] picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.id
     *
     * @return the value of bookinfo.id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.id
     *
     * @param id the value for bookinfo.id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.bname
     *
     * @return the value of bookinfo.bname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.bname
     *
     * @param bname the value for bookinfo.bname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.author
     *
     * @return the value of bookinfo.author
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.author
     *
     * @param author the value for bookinfo.author
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.press
     *
     * @return the value of bookinfo.press
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.press
     *
     * @param press the value for bookinfo.press
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setPress(String press) {
        this.press = press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.presstime
     *
     * @return the value of bookinfo.presstime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getPresstime() {
        return presstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.presstime
     *
     * @param presstime the value for bookinfo.presstime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setPresstime(Date presstime) {
        this.presstime = presstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.stock
     *
     * @return the value of bookinfo.stock
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.stock
     *
     * @param stock the value for bookinfo.stock
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setStock(Double stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.loan_mount
     *
     * @return the value of bookinfo.loan_mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getLoanMount() {
        return loanMount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.loan_mount
     *
     * @param loanMount the value for bookinfo.loan_mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setLoanMount(Double loanMount) {
        this.loanMount = loanMount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.mount
     *
     * @return the value of bookinfo.mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getMount() {
        return mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.mount
     *
     * @param mount the value for bookinfo.mount
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMount(Double mount) {
        this.mount = mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.bt_id
     *
     * @return the value of bookinfo.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getBtId() {
        return btId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.bt_id
     *
     * @param btId the value for bookinfo.bt_id
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setBtId(Integer btId) {
        this.btId = btId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.picture
     *
     * @return the value of bookinfo.picture
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.picture
     *
     * @param picture the value for bookinfo.picture
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
}