package com.kcsj.pojo;

import java.util.Date;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.eid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ecard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String ecard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ename
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.etel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer etel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.epass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String epass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.etime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date etime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.eid
     *
     * @return the value of emp.eid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.eid
     *
     * @param eid the value for emp.eid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ecard
     *
     * @return the value of emp.ecard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getEcard() {
        return ecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ecard
     *
     * @param ecard the value for emp.ecard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEcard(String ecard) {
        this.ecard = ecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ename
     *
     * @return the value of emp.ename
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ename
     *
     * @param ename the value for emp.ename
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.etel
     *
     * @return the value of emp.etel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getEtel() {
        return etel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.etel
     *
     * @param etel the value for emp.etel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEtel(Integer etel) {
        this.etel = etel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.epass
     *
     * @return the value of emp.epass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getEpass() {
        return epass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.epass
     *
     * @param epass the value for emp.epass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEpass(String epass) {
        this.epass = epass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.etime
     *
     * @return the value of emp.etime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.etime
     *
     * @param etime the value for emp.etime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }
}