package com.kcsj.pojo;

import java.util.Date;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String hname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hbtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date hbtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hrtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date hrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.overtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double overtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.money
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.assess
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String assess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.borrow_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String borrowHandle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.return_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String returnHandle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hid
     *
     * @return the value of history.hid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hid
     *
     * @param hid the value for history.hid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hname
     *
     * @return the value of history.hname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hname
     *
     * @param hname the value for history.hname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setHname(String hname) {
        this.hname = hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.sno
     *
     * @return the value of history.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.sno
     *
     * @param sno the value for history.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hbtime
     *
     * @return the value of history.hbtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getHbtime() {
        return hbtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hbtime
     *
     * @param hbtime the value for history.hbtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setHbtime(Date hbtime) {
        this.hbtime = hbtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hrtime
     *
     * @return the value of history.hrtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getHrtime() {
        return hrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hrtime
     *
     * @param hrtime the value for history.hrtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setHrtime(Date hrtime) {
        this.hrtime = hrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.overtime
     *
     * @return the value of history.overtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.overtime
     *
     * @param overtime the value for history.overtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setOvertime(Double overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.money
     *
     * @return the value of history.money
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.money
     *
     * @param money the value for history.money
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.assess
     *
     * @return the value of history.assess
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getAssess() {
        return assess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.assess
     *
     * @param assess the value for history.assess
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setAssess(String assess) {
        this.assess = assess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.borrow_handle
     *
     * @return the value of history.borrow_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getBorrowHandle() {
        return borrowHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.borrow_handle
     *
     * @param borrowHandle the value for history.borrow_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setBorrowHandle(String borrowHandle) {
        this.borrowHandle = borrowHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.return_handle
     *
     * @return the value of history.return_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getReturnHandle() {
        return returnHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.return_handle
     *
     * @param returnHandle the value for history.return_handle
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setReturnHandle(String returnHandle) {
        this.returnHandle = returnHandle;
    }
}