package com.kcsj.pojo;

import java.util.Date;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mcard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String mcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mtel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer mtel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mpass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String mpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mid
     *
     * @return the value of manager.mid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mid
     *
     * @param mid the value for manager.mid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mcard
     *
     * @return the value of manager.mcard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getMcard() {
        return mcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mcard
     *
     * @param mcard the value for manager.mcard
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMcard(String mcard) {
        this.mcard = mcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mname
     *
     * @return the value of manager.mname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mname
     *
     * @param mname the value for manager.mname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMname(String mname) {
        this.mname = mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mtel
     *
     * @return the value of manager.mtel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getMtel() {
        return mtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mtel
     *
     * @param mtel the value for manager.mtel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMtel(Integer mtel) {
        this.mtel = mtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mpass
     *
     * @return the value of manager.mpass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getMpass() {
        return mpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mpass
     *
     * @param mpass the value for manager.mpass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMpass(String mpass) {
        this.mpass = mpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mtime
     *
     * @return the value of manager.mtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mtime
     *
     * @param mtime the value for manager.mtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}