package com.kcsj.pojo;

import java.util.Date;

public class Reserve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.rid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.rno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer rno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.rtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date rtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.rbookname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String rbookname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.rid
     *
     * @return the value of reserve.rid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.rid
     *
     * @param rid the value for reserve.rid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.rno
     *
     * @return the value of reserve.rno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getRno() {
        return rno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.rno
     *
     * @param rno the value for reserve.rno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setRno(Integer rno) {
        this.rno = rno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.rtime
     *
     * @return the value of reserve.rtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getRtime() {
        return rtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.rtime
     *
     * @param rtime the value for reserve.rtime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setRtime(Date rtime) {
        this.rtime = rtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.rbookname
     *
     * @return the value of reserve.rbookname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getRbookname() {
        return rbookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.rbookname
     *
     * @param rbookname the value for reserve.rbookname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setRbookname(String rbookname) {
        this.rbookname = rbookname;
    }
}