package com.kcsj.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sdeptment
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String sdeptment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Integer stel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Date stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.smout
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double smout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno_return
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double snoReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno_borrow
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private Double snoBorrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.spass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    private String spass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sid
     *
     * @return the value of student.sid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sid
     *
     * @param sid the value for student.sid
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sdeptment
     *
     * @return the value of student.sdeptment
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getSdeptment() {
        return sdeptment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sdeptment
     *
     * @param sdeptment the value for student.sdeptment
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSdeptment(String sdeptment) {
        this.sdeptment = sdeptment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stel
     *
     * @return the value of student.stel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Integer getStel() {
        return stel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stel
     *
     * @param stel the value for student.stel
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setStel(Integer stel) {
        this.stel = stel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stime
     *
     * @return the value of student.stime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stime
     *
     * @param stime the value for student.stime
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.smout
     *
     * @return the value of student.smout
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getSmout() {
        return smout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.smout
     *
     * @param smout the value for student.smout
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSmout(Double smout) {
        this.smout = smout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno_return
     *
     * @return the value of student.sno_return
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getSnoReturn() {
        return snoReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno_return
     *
     * @param snoReturn the value for student.sno_return
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSnoReturn(Double snoReturn) {
        this.snoReturn = snoReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno_borrow
     *
     * @return the value of student.sno_borrow
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public Double getSnoBorrow() {
        return snoBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno_borrow
     *
     * @param snoBorrow the value for student.sno_borrow
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSnoBorrow(Double snoBorrow) {
        this.snoBorrow = snoBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.spass
     *
     * @return the value of student.spass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public String getSpass() {
        return spass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.spass
     *
     * @param spass the value for student.spass
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    public void setSpass(String spass) {
        this.spass = spass;
    }
}