package com.kcsj.dao;

import com.kcsj.pojo.Reserve;

public interface ReserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    int insert(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    int insertSelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    Reserve selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    int updateByPrimaryKeySelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated Mon May 22 08:40:29 CST 2017
     */
    int updateByPrimaryKey(Reserve record);
}